accounts/urls.py
from django.conf.urls import patterns, url
#from django.contrib.auth.views import login, logout
import views

urlpatterns=patterns('',
		url(r'^register/$', views.register),
		url(r'^login/$', views.login),
		url(r'^logout/$', views.logout),
		url(r'^welcome/$', views.welcome),
		url(r'^info/$', views.info),
		url(r'^(\d{1,})/$', views.homepage),
		)

qiubangmang/urls.py
from django.conf.urls import patterns, include, url
from views import index
import settings

# enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # enable the admin:
    url(r'^admin/', include(admin.site.urls)),
	('^$', index),
	# static dir
	(r'^site_medias/(?P<path>.*)$','django.views.static.serve',{'document_root':settings.STATICFILES_DIRS,'show_indexes':True}),
	url(r'^accounts/', include('accounts.urls')),
	url(r'^tasks/', include('tasks.urls')),
	url(r'^sells/', include('sells.urls')),
)

sells/urls.py
'''Url request dispatcher'''

from django.conf.urls import patterns, url
import views

urlpatterns = patterns('',
		url(r'^post/$', views.post),
		(r'^(\d{1,})/$', views.show_ability),
		(r'^$', views.show_all_abilities),
		)

accounts/models.py
from django.db import models
from django.contrib.auth.models import User

class UserProfile(models.Model):
	
	user=models.OneToOneField(User)

	sex=models.CharField(max_length=2, null = True)
	phone=models.CharField(max_length=15)
	qq=models.CharField(max_length=12, null = True)
	describe=models.CharField(max_length=100, null = True)
	acceptNUMBER=models.IntegerField()
	raiseNUMBER=models.IntegerField()
	userLEVEL=models.IntegerField()
	rp=models.IntegerField()

accounts/forms.py
#coding=utf-8
from django import forms
from django.contrib.auth.models import User
from django.utils.translation import ugettext_lazy as _

class RegisterForm(forms.Form):
    email=forms.EmailField(label=_(u"邮件"),max_length=30,widget=forms.TextInput(attrs={'size': 30,}))    
    username=forms.CharField(label=_(u"用户名"),max_length=20,widget=forms.TextInput(attrs={'size': 20,}))
    password=forms.CharField(label=_(u"密码"),max_length=10,widget=forms.PasswordInput(attrs={'size': 10,}))    
    sex=forms.CharField(label=_(u"性别"),max_length=2,widget=forms.TextInput(attrs={'size':2,}))
    phone=forms.CharField(label=_(u"手机号码"),max_length=15,widget=forms.TextInput(attrs={'size':15,}))
    qq=forms.CharField(label=_(u"QQ号"),max_length=12,widget=forms.TextInput(attrs={'size':12,}))
    describe=forms.CharField(label=_(u"自我描述"),max_length=100,widget=forms.TextInput(attrs={'size':100,}))
    
    def clean_username(self):
        '''验证重复昵称'''
        users = User.objects.filter(username__iexact=self.cleaned_data["username"])
        if not users:
            return self.cleaned_data["username"]
        raise forms.ValidationError(_(u"该昵称已经被使用请使用其他的昵称"))
        
    def clean_email(self):
        '''验证重复email'''
        emails = User.objects.filter(email__iexact=self.cleaned_data["email"])
        if not emails:
            return self.cleaned_data["email"]
        raise forms.ValidationError(_(u"该邮箱已经被使用请使用其他的"))
        
class LoginForm(forms.Form):
    username=forms.CharField(label=_(u"用户名"),max_length=30,widget=forms.TextInput(attrs={'size': 20,}))
    password=forms.CharField(label=_(u"密码"),max_length=30,widget=forms.PasswordInput(attrs={'size': 20,}))
    

accounts/views.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate, login as auth_login, logout as auth_logout
from django.contrib.auth.models import User
from django.http import HttpResponseRedirect, HttpResponse, Http404
from django.shortcuts import render_to_response
from forms import RegisterForm, LoginForm
from django.template import RequestContext
from tasks.models import Mission
from sells.models import Ability
from accounts.models import UserProfile

def register(request):
    template_var = {}
    form = RegisterForm()
    if request.method == "POST":
        form = RegisterForm(request.POST.copy())
        if form.is_valid():
            username = form.cleaned_data["username"]
            email = form.cleaned_data["email"]
            password = form.cleaned_data["password"]
            sex = form.cleaned_data["sex"]
            phone = form.cleaned_data["phone"]
            qq = form.cleaned_data["qq"]
            describe = form.cleaned_data["describe"]
            user = User.objects.create_user(username, email, password)
            user.save()
            user_pro = UserProfile(user = user, 
            	sex = sex, phone = phone, qq = qq, describe = describe,
            	acceptNUMBER = 0, raiseNUMBER = 0, userLEVEL = 0, rp = 0)
            user_pro.save()
            _login(request, username, password)
            return HttpResponseRedirect("/accounts/welcome")
    template_var["form"] = form
    return render_to_response("accounts/register.html", template_var, context_instance = RequestContext(request))

def login(request):
	template_var={}
	form=LoginForm()
	if request.method=="POST":
		form=LoginForm(request.POST.copy())
		if form.is_valid():
			_login(request,form.cleaned_data['username'],form.cleaned_data['password'])
			return HttpResponseRedirect("/accounts/welcome/")
	template_var['form']=form
	return render_to_response("accounts/login.html",template_var,context_instance=RequestContext(request))

def welcome(request):
	if request.user.is_authenticated():
		username=request.user.username
		url=request.get_full_path()
		return render_to_response('accounts/welcome.html', {'username': username, 'url': url, })
	else:
		return HttpResponseRedirect("/accounts/login/")

def _login(request, username, password):
	ret=False
	user=authenticate(username=username, password=password)
	if user:
		if user.is_active:
			auth_login(request, user)
			ret=True
		else:
			print '1'
	else:
		print '2'
	return ret

def logout(request):
	auth_logout(request)
	return HttpResponseRedirect("/")

def homepage(request, user_id):
	if request.user.is_authenticated():
		try:
			user=User.objects.get(id=user_id)
		except:
			raise Http404()
		received_tasks = Mission.objects.filter(missionRAISER=user).exclude(missionRECEIVER=None)
		unreceived_tasks = Mission.objects.filter(missionRAISER=user, missionRECEIVER=None)
		received_abilities=Ability.objects.filter(abilityRAISER=user).exclude(abilityRECEIVER=None)
		unreceived_abilities=Ability.objects.filter(abilityRAISER=user, abilityRECEIVER=None)
		user_profile = UserProfile.objects.get(user=user)
		return render_to_response("accounts/homepage.html", {'request': request, 'user': user, 'user_profile': user_profile, 'received_tasks': received_tasks, 'unreceived_tasks': unreceived_tasks, 'received_abilities': received_abilities, 'unreceived_abilities': unreceived_abilities, })
	return HttpResponseRedirect("/accounts/login/")

def info(request):
	if request.user.is_authenticated():
		try:
			user = User.objects.get(id=request.user.id)
			user_pro = UserProfile.objects.get(user=user)
			form = RegisterForm()
			email_judge = False
			username_judge = False
			if request.method == 'POST':
				form = RegisterForm(request.POST.copy())
				if form.is_valid():
					email = form.cleaned_data["email"]
					username = form.cleaned_data["username"]
					password = form.cleaned_data["password"]
					sex = form.cleaned_data["sex"]
					phone = form.cleaned_data["phone"]
					qq = form.cleaned_data["qq"]
					describe = form.cleaned_data["describe"]
					#for judege
					try:
						tmp = User.objects.get(email = email)
						if tmp.id != user.id: email_judge = True
						else: email_judge = False
					except:	
						email_judge = False
					try:
						tmp = User.objects.get(username = username)
						if tmp.id != user.id: username_judge = True
						else: username_judge = False
					except:	
						username_judge = False
					if email_judge or username_judge:
						return render_to_response("accounts/info.html", {'email_judge':email_judge, 'username_judge':username_judge, }) 
					else:
						user.email = email
						user.username = username
						user.set_password(password)
						user_pro.sex = sex
						user_pro.phone = phone
						user_pro.qq = qq
						user_pro.describe = describe
						user.save()
						user_pro.save()
						return HttpResponseRedirect("/")
			return render_to_response("accounts/info.html", {'email_judge':email_judge, 'username_judge':username_judge, })
		except:
			raise Http404()
	return HttpResponseRedirect("/accounts/login/")

templates/accounts/homepage.html
<html>
	<head>
		<title>{{ user.username }}的主页</title>
	</head>
	<body background="../../site_medias/snorlax.jpg">
		<h1><font color="orange">{{ user.username }}的主页</font></h1>
		<hr>
		<p><font color="orange">个人描述：{{ user_profile.describe }}</font></p>
		<p><font color="orange">人品值：{{ user_profile.rp }}</font></p>
		<table border="1" bgcolor="green">
			<tr>
				<th></th><th><font color="orange">任务</font></th><th><font color="orange">能力</th>
			</tr>
			<tr>
				<th><font color="orange">未被接受</font></th>
				<th>
					<ul>
						{% for task in unreceived_tasks %}
							<li>
								<a href="/tasks/{{ task.id }}/"><font color="orange">{{ task.missionNAME }}</font></a>
							</li>
						{% endfor %}
					</ul>
				</th>
				<th>
					<ul>
						{% for ability in unreceived_abilities %}
							<li>
								<a href="/sells/{{ ability.id }}/"><font color="orange">{{ ability.abilityNAME }}</font></a>
							</li>
						{% endfor %}
					</ul>
				</th>
			</tr>
			<tr>
				<th><font color="orange">已被接受</font></th>
				<th>
					<ul>
						{% for task in received_tasks %}
							<li>
								<a href="/tasks/{{ task.id }}/"><font color="orange">{{ task.missionNAME }}</font></a>
							</li>
						{% endfor %}
					</ul>
				</th>
				<th>
					<ul>
						{% for ability in received_abilities %}
							<li>
								<a href="/sells/{{ ability.id }}/"><font color="orange">{{ ability.abilityNAME }}</font></a>
							</li>
						{% endfor %}
					</ul>
				</th>
			</tr>
			<tr>
				<th><font color="orange">待完成</font></th>
				<th colspan="2">
					<ul>
						{% for task in my_tasks %}
							{% if not task.closed %}
							<li>
								<a href="/tasks/{{ task.id }}/"><font color="orange">{{ task.missionNAME }}</font></a>
							</li>	
							{% endif %}
						{% endfor %}
					</ul>	
				</th>
			</tr>
			<tr>
				<th><font color="orange">已完成</font></th>
				<th colspan="2">
					<ul>
						{% for task in my_tasks %}
							{% if task.closed %}
							<li>
								<a href="/tasks/{{ task.id }}/"><font color="orange">{{ task.missionNAME }}</font></a>
							</li>	
							{% endif %}
						{% endfor %}
					</ul>	
				</th>
			</tr>
		</table>
		<hr>
		<p><a href="/"><font color="orange">返回主页</font></a></p>
		<p><a href="/accounts/info/"><font color="orange">修改个人信息</font></a></p>
	</body>
</html>

templates/accounts/info.html
<html>
	<head>
		<title>球帮忙-修改个人信息</title>
	</head>
	<body>
		<h1>修改个人信息</h1>
		<form action="" method="post">
			{% if email_judge %}
			<ul><li>该邮箱已经被使用请使用其他的</li></ul>
			{% endif %}
			<p><label for="id_email">邮件:</label> <input id="id_email" maxlength="30" name="email" size="30" type="text" /></p>
			{% if username_judge %}
			<ul><li>该用户名已经被使用请使用其他的</li></ul>
			{% endif %}
			<p><label for="id_username">用户名:</label> <input id="id_username" maxlength="20" name="username" size="20" type="text" /></p>
			<p><label for="id_password">密码:</label> <input id="id_password" maxlength="10" name="password" size="10" type="password" /></p>
			<p><label for="id_sex">性别:</label> <input id="id_sex" maxlength="2" name="sex" size="2" type="text" /></p>
			<p><label for="id_phone">手机号码:</label> <input id="id_phone" maxlength="15" name="phone" size="15" type="text" /></p>
			<p><label for="id_qq">QQ号:</label> <input id="id_qq" maxlength="12" name="qq" size="12" type="text" /></p>
			<p><label for="id_describe">自我描述:</label> <input id="id_describe" maxlength="100" name="describe" size="100" type="text" /></p>
			<input type="submit" value="确认">
		</form>
	</body>
</html>

templates/accounts/login.html
<html>
	<head>
		<title>球帮忙-登录</title>
	</head>
	<body>
		{% if messages %}
			<ul>
				{% for message in messages %}
					<li>{{ message }}</li>
				{% endfor %}
			</ul>
		{% endif %}

		<form action="" method="post">{% csrf_token %}
			<table border="0" cellpadding="0">
				{{ form.as_table }}
			</table>
			<p> <a href="{% url 'accounts.views.register' %}">注册</a> <a href="{% url 'qiubangmang.views.index' %}">返回首页</a> <input type="submit" value="登录" /></p>
		</form>
	</body>
</html>

templates/accounts/register.html
<html>
	<head>
		<title>球帮忙-注册</title>
	</head>
	<body>
		<h1>注册</h1>
		<form action="" method="post">
			{{ form.as_p }}
			<input type="submit" value="创建账户">
		</form>
	</body>
</html>

templates/accounts/welcome.html
<html>
	<head>
		<title>欢迎！</title>
		<!--meta http-equiv="refresh" content="5; url={{ url }}"--!>
	</head>
	<body>
		<p>欢迎回来，{{ username }}！<span id="totalSecond">5</span>秒后跳转到登录前页面。</p>
		<hr>
		<p><a href="/">返回主页</a></p>

		<script language="javascript" type="text/javascript">
			var second=document.getElementById('totalSecond').textContent;

			if (navigator.appName.indexOf("Explorer")>-1){
				second=document.getElementById('totalSecond').innerText;
			} else {
				second=document.getElementById('totalSecond').textContent;
			}

			setInterval("redirect()", 1000);

			function redirect(){
				if (second<1){
					location.href="/";
				} else {
					if (navigator.appName.indexOf("Explorer")>-1){
						document.getElementById('totalSecond').innerText=second--;
					} else {
						document.getElementById('totalSecond').textContent=second--;
					}
				}
			}
		</script>
	</body>
</html>