qiubangmang/urls.py
from django.conf.urls import patterns, include, url
from views import index
import settings

# enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # enable the admin:
    url(r'^admin/', include(admin.site.urls)),
	('^$', index),
	# static dir
	(r'^site_medias/(?P<path>.*)$','django.views.static.serve',{'document_root':settings.STATICFILES_DIRS,'show_indexes':True}),
	url(r'^accounts/', include('accounts.urls')),
	url(r'^tasks/', include('tasks.urls')),
	url(r'^sells/', include('sells.urls')),
)

sells/urls.py
'''Url request dispatcher'''

from django.conf.urls import patterns, url
import views

urlpatterns = patterns('',
		url(r'^post/$', views.post),
		(r'^(\d{1,})/$', views.show_ability),
		(r'^$', views.show_all_abilities),
		)

tasks/urls.py
'''Url request dispatcher'''

from django.conf.urls import patterns, url
import views

urlpatterns = patterns('',
		url(r'^post/$', views.post),
		(r'^(\d{1,})/$', views.show_task),
		(r'^$', views.show_all_tasks),
		)

tasks/models.py
from django.db import models
from django.contrib.auth.models import User

class Mission(models.Model):
	'''Mission model

	follow database design doc'''

	missionNAME = models.CharField(max_length=80)
	missionDESCRIBE = models.TextField(max_length=1000)
	logDATE = models.DateTimeField()
	deadline = models.DateTimeField()
	rpBONUS = models.PositiveIntegerField()
	missionRAISER = models.ForeignKey(User, related_name='User_missionRAISER')
	missionRECEIVER = models.ForeignKey(User, related_name='User_missionRECEIVER', null=True)
	acceptDATE = models.DateTimeField(null=True)
	closed = models.BooleanField()

tasks/forms.py
# --coding: utf-8 --
from django import forms
from django.utils.translation import ugettext_lazy as _

class PostForm(forms.Form):
	title=forms.CharField(label=_(u'主题'), max_length=80, widget=forms.TextInput(attrs={'size' : 20, }))
	content=forms.CharField(label=_(u'内容'), max_length=1000, widget=forms.Textarea)
	bonus=forms.CharField(label=_(u'悬赏'), widget=forms.TextInput)
	deadline = forms.CharField(label=_(u'截止日期'), widget=forms.TextInput)

	def valid(self):
		'''check the validation of PostForm

		check if bonus is positive, length of title, content valid'''

		if self.is_valid():
			try:
				bonus_no=int(self.cleaned_data['bonus'])
				title=self.cleaned_data["title"]
				content=self.cleaned_data["content"]
				if bonus_no>=0 and len(title) <= 80 and len(content) <= 1000:
					return True
			except:
				return False
		return False

tasks/views.py
#-- coding:utf-8 --
'''Process all request relatived to tasks

include post and show page'''

import datetime
from django import forms
from django.http import HttpResponseRedirect, HttpResponse, Http404
from django.shortcuts import render_to_response
from django.template import RequestContext
from django.contrib.auth import authenticate
from django.contrib.auth.models import User
from models import Mission
from forms import PostForm
from reply.forms import ReplyForm
from reply.models import Reply
from accounts.models import UserProfile

def post(request):
	'''process post page

	judge user's authenticate status and save valid post, store raiseNUMBER of user'''

	if request.user.is_authenticated():
		form = PostForm()
		if request.method == "POST":
			form = PostForm(request.POST.copy())
			if form.valid():
				poster = request.user
				title = form.cleaned_data["title"]
				content = form.cleaned_data["content"]
				bonus = form.cleaned_data["bonus"]
				deadline = form.cleaned_data["deadline"]
				post = Mission(missionNAME=title, missionDESCRIBE=content,
						logDATE=datetime.datetime.now(), deadline=deadline,
						rpBONUS=bonus, missionRAISER=poster, closed=False)
				post.save()

				poster_pro = UserProfile.objects.get(user_id=request.user.id) 
				poster_pro.raiseNUMBER += 1
				poster_pro.save()
				return HttpResponseRedirect("/")
		form = PostForm()
		return render_to_response("tasks/post.html",{'request': request, 'form': form, })
	return HttpResponseRedirect("/accounts/login/")

def show_task(request,no):
	'''process show task page

	judge the kind of request user post and dispatch'''

	if request.user.is_authenticated():
		form = ReplyForm()
		try:
			no = int(no)
			task = Mission.objects.get(id=no)
			if task.closed:
				return HttpResponseRedirect("/accounts/%s/" % request.user.id)
			raiser_id = task.missionRAISER.id
			if task.missionRECEIVER:
				receiver_id = task.missionRECEIVER.id
				is_receiver = request.user.id == receiver_id
			else:
				is_receiver = False
			is_raiser = request.user.id == raiser_id
		except:
			raise Http404()

		if request.method == 'POST':
			print request.POST
			if request.POST.has_key('receive') and request.POST['receive'] == u'领   取':
				receive(request, task)
			if request.POST.has_key('finish') and request.POST['finish'] == u'结   算':
				finish(request, task)
			if request.POST.has_key('reply_tag'):
				save_reply(form, request, task)
			return HttpResponseRedirect("/tasks/%s/" % no)
		else:
			replies = Reply.objects.filter(berepliedMISSION=task)
			return render_to_response("tasks/showtask.html", {'request':request, 'task': task, 'form': ReplyForm, 'replies': replies,'is_raiser':is_raiser, 'is_receiver':is_receiver})
	return HttpResponseRedirect("/accounts/login/")

def show_all_tasks(request):
	tasks = Mission.objects.all()
	return render_to_response('tasks/task.html',
			{'request': request, 'tasks': tasks, })

def receive(request, task):
	'''Tool method for save task'''

	task_raiser = task.missionRAISER
	if request.user != task_raiser:
		if not task.missionRECEIVER:
			task.missionRECEIVER = request.user
			task.acceptDATE = datetime.datetime.now()
			task.save()

def save_reply(form, request, task):
	'''Tool method for save reply'''

	content = request.POST['content']
	reply = Reply(replyTIME=datetime.datetime.now(), replyUSER=request.user, berepliedMISSION=task, replyWORDS=content)
	reply.save()

def finish(request, task):

	task.closed = True;
	task.save()
	receiver_pro = UserProfile.objects.get(user_id = task.missionRECEIVER.id)
	receiver_pro.rp += task.rpBONUS;
	receiver_pro.userLEVEL = 1+receiver_pro.rp/100
	receiver_pro.save()

templates/tasks/post.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<link rel="stylesheet" type="text/css" href="../../site_medias/css/logo.css" />
<link rel="stylesheet" type="text/css" href="../../site_medias/css/siteHeader.css"/>
<link rel="stylesheet" type="text/css" href="../../site_medias/css/note.css" />
<title>无标题文档</title>
<style>
	.container{
		margin:0 auto;
		width:960px;
	}
        #id_title{
            width: 380px;
        }
        #id_content{
            width: 380px;
        }
        #id_bonus{
            width: 380px;
        }
        #id_deadline{
            width: 380px;
        }
</style>
</head>

<body>
	<div class="container">
    <header>
  		<div id="siteHeader" style="left: 0px;">
        	<div id="siteHeaderInner">
            	<ul class="siteHeaderGlovalNavigation">
                	<li><a href="/"><span>首页</span></a></li>
                    <li><a href="/tasks"><span>任务</span></a></li>
                    <li><a href="/sells"><span>能力</span></a></li>
                </ul>
                
                <ul class="siteHeaderMenuList">
                	{% if request.user.is_authenticated %}
                    <li id="siteHeaderNotification" >
                    <a href="/accounts/{{ request.user.id }}">
					<span id="siteHeaderUserNickNameContainer">Hi,{{ request.user.username }}</span>
					</a>
                    </li>
                    <li id="siteHeaderHorizon"><a href="/post"><span>发布任务</span></a></li>
                    <li id="siteHeaderHorizon"><a href="/sells/post"><span>展示能力</span></a></li>
                    <li class="siteHeaderHorizon"><a href="/accounts/logout"><span>登出</span></a>
                    </li>
                    {% else %}
                    <li id="siteHeaderNotification" class="siteHeaderLogin">
						<a href="/accounts/register"><span>注册</span></a>
					</li>
					<li id="siteHeaderNotification" class="siteHeaderLogin">
						<a href="/accounts/login"><span>登录</span></a>
					</li>
                    {% endif %}
                </ul>
            </div>
        </div>
        
        <div id="logo">
        	<a href="/"><img src="../../site_medias/img/logo_ver2.png" /></a>
        </div>
  </header>
	<form action="" method="post">{% csrf_token %}
			<table border="0" cellpadding="0">
				{{ form.as_table }}
			</table>
			<p><input type="submit" value="发布" class="button red"/></p>
		</form>
    </div>
</body>
</html>

templates/tasks/showtask.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<link rel="stylesheet" type="text/css" href="../../site_medias/css/siteHeader.css"/>
<link rel="stylesheet" type="text/css" href="../../site_medias/css/logo.css" />
<link rel="stylesheet" type="text/css" href="../../site_medias/css/taskInfo.css" />
<link rel="stylesheet" type="text/css" href="../../site_medias/css/note.css" />
<link rel="stylesheet" type="text/css" href="../../site_medias/css/messageContainer.css" />
<title>无标题文档</title>
</head>

<body>
	<div class="container">
        <header>
            <div id="siteHeader" style="left: 0px;">
                <div id="siteHeaderInner">
                    <ul class="siteHeaderGlovalNavigation">
                        <li><a href="/"><span>首页</span></a></li>
                        <li><a href="/tasks/"><span>任务</span></a></li>
                        <li><a href="/sells/"><span>能力</span></a></li>
                    </ul>
                    <ul class="siteHeaderMenuList">
                        {% if request.user.is_authenticated %}
                        <li id="siteHeaderNotification" >
                        <a href="/accounts/{{ request.user.id }}">
                        <span id="siteHeaderUserNickNameContainer">Hi,{{ request.user.username }}</span>
                        </a>
                        <li id="siteHeaderHorizon"><a href="/tasks/post"><span>发布任务</span></a></li>
                        <li id="siteHeaderHorizon"><a href="/sells/post"><span>展示能力</span></a></li>
                        <li class="siteHeaderHorizon"><a href="/accounts/logout"><span>登出</span></a></li>
                        {% else %}
                        <li id="siteHeaderNotification" class="siteHeaderLogin">
                        <a href="/accounts/login"><span>登入</span></a>

                    </li>
                    <li id="siteHeaderNotification" class="siteHeaderLogin">
                        <a href="/accounts/register"><span>注册</span></a>
                                                                    
                    </li>
                    {% endif %}
                </ul>
                </div>
            </div>
            <div id="logo">
                <a href="/"><img src="../../site_medias/img/logo_ver2.png" /></a>
            </div>
        </header>
        		<div class="note">
                <ul>
                	{% if task.missionRECEIVER %}
                	<li>
                    <a href="/accounts/{{ task.missionRECEIVER.id }}/">
                    <h2>已领取！</h2>
                    <p>此任务已被{{ task.missionRECEIVER.username }}于{{ task.acceptDATE }}领取</p></a>

                    </li>
                    {% else %}
                    	<li>
						<a href="#">
                        <h2>未领取！</h2>
                        <p>此任务还没有被领取，点击下方按钮领取！</p>
                        </a>
                        </li>
                        
                    {% endif %}
                    
                </ul>
				</div>
                <!--div class="messageContainer">
                    <p></p>
                    <p></p>
                    <br>
                    
                    <br>
                    <p></p>
                    <p>截止日期：{{ task.deadline|date:"Y-m-d H:i:s" }}</p-->
                    <div id="container">

                        <div class="bubble">
                            <div class="rectangle"><h2>{{ task.missionNAME }}</h2></div>
                            <div class="triangle-l"></div> <!-- Left triangle -->
                            <div class="triangle-r"></div> <!-- Right triangle -->
                            <div class="info">
                            <h2>悬赏：{{ task.rpBONUS }}</h2>
                            <p>发布日期：{{ task.logDATE|date:"Y-m-d H:i:s" }}</p>
                            <p>{{ task.missionDESCRIBE }}</p>
                            <p>截止日期：{{ task.deadline|date:"Y-m-d H:i:s" }}</p>
                            <p>发布者：<a href="/accounts/{{ task.missionRAISER.id }}/">{{ task.missionRAISER.username }}</a></p>

                            <form action="" method="post">{% csrf_token %}
                                {% if task.missionRECEIVER %}
                                {% if is_raiser %}
                              <p><input id = "finish" name = "finish" type="submit" value="结   算" class="button blue" /></p>
                                {% endif %}
                                {% else %}
                                {% if not is_raiser %}
                            <p><input id = "receive" name = "receive" type="submit" value="领   取" class="button blue" /></p>
                                {% endif %}
                                {% endif %}

                        	</form>
                            </div>
                        </div>
                    	
                                    <style>.messagebox{margin:30px 0 0 0;} .messagebox p{font-size: 15px;}</style>
                        	<div class="messagebox" >
                                <ul>
                                {% for reply in replies %}
                                    <li>
                                    <p>{{ reply.replyUSER.username }}于{{ reply.replyTIME|date:"Y-m-d H:i:s" }}写道：</p>
                                    <p>      {{ reply.replyWORDS }}</p>
                                    <!--form action="" method="post">{% csrf_token %}
                                        {{ form_for_reply.as_table }}
                                        <p><input type="submit" value="回复" /></p>
                                    </form-->
                                    </li>
                                    <br>
                                {% endfor %}
                                </ul>
                                </div>

                            <form action="" method="post">{% csrf_token %}
                            <table border="0" cellpadding="0">
                                    {{ form.as_table }}
                                </table>
                                                            <p><input type="submit" value="回   复" class="button green"/></p>
                            
                        </form>
                    </div>
                </div>
                <br>
                
                <br>
                
		<hr>
		<a href="/">回到主页</a>
		
		<!-- Duoshuo Comment BEGIN -->
        <div class="ds-thread"></div>
        <script type="text/javascript">
        var duoshuoQuery = {short_name:"qiubangmang"};
        (function() {
            var ds = document.createElement('script');
            ds.type = 'text/javascript';ds.async = true;
            ds.src = 'http://static.duoshuo.com/embed.js';
            ds.charset = 'UTF-8';
            (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(ds);
        })();
        </script>
        <!-- Duoshuo Comment END -->
	</div>

</body>
</html>

templates/tasks/task.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<link rel="stylesheet" type="text/css" href="../../site_medias/css/task.css" />
<link rel="stylesheet" type="text/css" href="../../site_medias/css/siteHeader.css"/>
<link rel="stylesheet" type="text/css" href="../../site_medias/css/logo.css" />
<script type="text/javascript" src="../../site_medias/js/time_minus.js"></script>
<script type="text/javascript" src="../../site_medias/js/jquery-1.9.1.min.js"></script>
<!--link rel="stylesheet" type="text/css" href="css/note.css" /-->
<link  href="http://fonts.googleapis.com/css?family=Reenie+Beanie:regular" rel="stylesheet" type="text/css">
<script type="text/javascript" src="../../site_medias/js/jquery.wookmark.js"></script> 


<title>无标题文档</title>

</head>

<body>

<div class="container" >
  <header>
  		<div id="siteHeader" style="left: 0px;">
        	<div id="siteHeaderInner">
            	<ul class="siteHeaderGlovalNavigation">
                	<li><a href="/"><span>首页</span></a></li>
                    <li><a href="/tasks/"><span>任务</span></a></li>
                    <li><a href="/sells/"><span>能力</span></a></li>
                </ul>
                
                <ul class="siteHeaderMenuList">
                	{% if request.user.is_authenticated %}
                    <li id="siteHeaderNotification" >
                    <a href="/accounts/{{ request.user.id }}">
					<span id="siteHeaderUserNickNameContainer">Hi,{{ request.user.username }}</span>
					</a>
                    </li>
                    <li id="siteHeaderHorizon"><a href="/post"><span>发布任务</span></a></li>
                    <li id="siteHeaderHorizon"><a href="/sells/post"><span>展示能力</span></a></li>
                    <li class="siteHeaderHorizon"><a href="/accounts/logout"><span>登出</span></a>
                    </li>
                    {% else %}
                    <li id="siteHeaderNotification" class="siteHeaderLogin">
                        <a href="/accounts/login"><span>登入</span></a>

                    </li>
                    <li id="siteHeaderNotification" class="siteHeaderLogin">
                        <a href="/accounts/register"><span>注册</span></a>
                                                                    
                    </li>
                    {% endif %}
                </ul>
            </div>
        </div>
        
        <div id="logo">
        	<a href="/"><img src="../../site_medias/img/logo_ver2.png" /></a>
        </div>
  </header>
  
<div class="waterFall" >

<ul id="wf"> 
	{% for mission in tasks%}
   <a href="/tasks/{{ mission.id }}">
    <li ><style>#wf li:hover{background-color:#F00;opacity:0.5;}#wf li{width:200px;}</style>
        <h2>{{mission.missionNAME}}</h2><p>{{mission.missionDESCRIBE}}
    </p>
    </li>
    </a>
    {% endfor %}
    <li width="200">
    	<h2>Example</h2>

    	<img src="../../site_medias/img/blue-bg.jpg" width="200" height="200" /><p>Here is details</p>
    </li>
    <li>
    	<img src="../../site_medias/img/blue-bg.jpg" width="200" height="300" /><p>Expmple</p>
    </li>
    <li>
    	<img src="../../site_medias/img/default-image.png" width="200" height="400" /><p>Example</p>
    </li>
    <li>
    	<img src="../../site_medias/img/default-image.png" width="200" height="200" /><p>Example</p>
    </li>
</ul>

 </div>
</div>

<script type="text/javascript">
$("#wf li").wookmark({ 
    container:$("#wf"), 
    offset:20, 
    itemWidth:200 
}); 

</script>
</body>
</html>